clc; clear;
spoon1 = load('ironcup_spoon_1.txt');
spoon2 = load('ironcup_spoon_2.txt');
spoon3 = load('ironcup_spoon_3.txt');
acrylic1 = load('ironcup_acrylic_1.txt');
acrylic2 = load('ironcup_acrylic_2.txt');
acrylic3 = load('ironcup_acrylic_3.txt');
al_ruler1 = load('ironcup_al_ruler_1.txt');
al_ruler2 = load('ironcup_al_ruler_2.txt');
al_ruler3 = load('ironcup_al_ruler_3.txt');

n = 500;
s = 860;
spoon1_cut = spoon1(s:s+n,:);
s = 850;
spoon2_cut = spoon2(s:s+n,:);
s = 740;
spoon3_cut = spoon3(s:s+n,:);
s = 1120;
acrylic1_cut = acrylic1(s:s+n,:);
s = 1000;
acrylic2_cut = acrylic2(s:s+n,:);
s = 840;
acrylic3_cut = acrylic3(s:s+n,:);
s = 1450;
al_ruler1_cut = al_ruler1(s:s+n,:);
s = 970;
al_ruler2_cut = al_ruler2(s:s+n,:);
s = 720;
al_ruler3_cut = al_ruler3(s:s+n,:);

figure;
subplot(9,1,1);
plot(spoon1_cut(:,2));
subplot(9,1,2);
plot(spoon2_cut(:,2));
subplot(9,1,3);
plot(spoon3_cut(:,2));
subplot(9,1,4);
plot(acrylic1_cut(:,2));
subplot(9,1,5);
plot(acrylic2_cut(:,2));
subplot(9,1,6);
plot(acrylic3_cut(:,2));
subplot(9,1,7);
plot(al_ruler1_cut(:,2));
subplot(9,1,8);
plot(al_ruler2_cut(:,2));
subplot(9,1,9);
plot(al_ruler3_cut(:,2));


save('cut_ironcup_spoon_1.txt','spoon1_cut','-ascii');
save('cut_ironcup_spoon_2.txt','spoon2_cut','-ascii');
save('cut_ironcup_spoon_3.txt','spoon3_cut','-ascii');
save('cut_ironcup_acrylic_1.txt','acrylic1_cut','-ascii');
save('cut_ironcup_acrylic_2.txt','acrylic2_cut','-ascii');
save('cut_ironcup_acrylic_3.txt','acrylic3_cut','-ascii');
save('cut_ironcup_al_ruler_1.txt','al_ruler1_cut','-ascii');
save('cut_ironcup_al_ruler_2.txt','al_ruler2_cut','-ascii');
save('cut_ironcup_al_ruler_3.txt','al_ruler3_cut','-ascii');